### DISCUSSION TITLE
Get the value of a key, without a class

### DISCUSSION THREAD

**Discussion by rodrigodevelms** [charleskorn/kaml#401] [General]
Is it possible to access the value of a key, without the need for a class?

`fun getValueFromYaml ( key: String, yamlPath: String) : String {}`

```

yaml
person:
    name: John
    age:  33
    childrens:
         - John Kid one
         - John kid two
```
         
         
```
  val name = getValueFromYaml ( "name", "/home/some_user/test.yaml")
  
 println(name)  *** John ****
```
