### DISCUSSION TITLE
Is there a way to omit specially formatted keys in strict mode deserialization?

### DISCUSSION THREAD

**Discussion by sefholt** [charleskorn/kaml#595] [Q&A] [answered]
I am working with format that allows  specially-formatted arbitrary keys.

Given the following model
```kotlin
@Serializable
data class Sample(
    val key: String,
    val key2: String,
)
```
I can have the following YAML that should be deserialized correctly in my case
```yaml
sample:
  key: value
  key2: value
  -omit-me: true
  -and-me: "definitely"
  -this-could-be-any-key: true
```

In this example I'd like to be able to use strict mode to automatically verify all mandatory keys (`key`, `key2`), but at the same time I'd like to be able to ignore all specially-formatted keys (containing dash at start, for instance).

As of now I'm getting exceptions like this (redacted from original to match sample):

```
UnknownPropertyException at -omit-me on line 4, column 1: Unknown property '-omit-me'.
    Known properties are: key, key2
    at com.charleskorn.kaml.YamlObjectInput.decodeElementIndex(YamlObjectInput.kt:52)
```

Is there a way to do so?
