### DISCUSSION TITLE
Are Multiple Sequence Styles Possible In Output?

### DISCUSSION THREAD

**Discussion by adamsmd** [charleskorn/kaml#707] [Q&A] [answered]
Is there a way to serialize to YAML that is formatted like the following, where `id` and `pages` are flow style, but other things like `children` are block style?

```yaml
root:
  children:
    - child1:
        aliases: ["name1", "name2"]
        pages: ["4", "6-7"]
        children:
          - child2:
              ...
          - child3:
              ...
```
