### ISSUE TITLE
How to remove type information with polymorphic output?

### ISSUE THREAD

**Issue by johanvergeer** [charleskorn/kaml#175]
I'm working on a dsl for [Azure DevOps YAML Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema) and they have a block called `variables` that can contain a few types.

```yaml
variables:
  # a variable can be created in 2 different ways
  - myVar:  'myVarValue'
  - name: myVar
     value: 'myVarValue'
     readonly: true
  # a group can be created in 1 way, but always has the same key
  - group: myFirstGroup
  - group: mySecondGroup
  - group: myThirdGroup
```

I've been working on this for a while now and by now I have been able to create a list of `Variable`

```kotlin
@Serializable
abstract class VariableBase {
    abstract val name: String
}

@Serializable
class Variable(override val name: String, val value: String, val readonly: Boolean = false) : VariableBase()

@Serializable
data class Group(override val name: String) : VariableBase()

@Serializable
class Variables {
    var variables = mutableListOf<VariableBase>()

    fun variable(name: String, value: String, readonly: Boolean = false) {
        this.variables.add(Variable(name, value, readonly))
    }

    fun group(name: String) {
        this.variables.add(Group(name))
    }
}

val variables = Variables()
variables.variable("myVar", "myValue")
variables.group("myFirstGroup")
variables.group("mySecondGroup")
variables.group("myThirdGroup")

val result = Yaml(
    configuration = YamlConfiguration(
        polymorphismStyle = PolymorphismStyle.Property
    ),
    serializersModule = SerializersModule {
        polymorphic(VariableBase::class) {
            subclass(Variable::class)
            subclass(Group::class)
        }
    })
    .encodeToString(Variables.serializer(), variables)

print(result)
```

This will generate the following output:

```yaml
variables:
- type: "Variable"
  name: "myVar"
  value: "myValue"
  readonly: false
- type: "Group"
  name: "myFirstGroup"
- type: "Group"
  name: "mySecondGroup"
- type: "Group"
  name: "myThirdGroup"
```

So how would I be able to create the list that is required to create an Azure DevOps YAML Pipeline variables block?

I guess it might be an idea to add a `PolymorphismStyle.None` to prevent a type output. I'll create a PR if you think that is a good idea.

**Comment by johanvergeer** [comment]
I was just able to rename the `name` field of the `Group` class to `group` using `@SerialName("group")`

```kotlin
@Serializable
data class Group(@SerialName("group") override val name: String) : VariableBase()
```

This gives the following output and brings me one step closer to the solution.

```yaml
variables:
- type: "Variable"
  name: "myVar"
  value: "myValue"
  readonly: false
- type: "Group"
  group: "myFirstGroup"
- type: "Group"
  group: "mySecondGroup"
- type: "Group"
  group: "myThirdGroup"
```

Now I just need to get rid of the `type` field. Do you think my previous suggestion will work?
