### ISSUE TITLE
Option to resolve $ref style references

### ISSUE THREAD

**Issue by jakobkmar** [charleskorn/kaml#217]
### Describe the problem you'd like to solve

![image](https://user-images.githubusercontent.com/52456572/146706274-9b8f53c9-5ec1-418c-af5a-cf02524c7680.png)
I want to resolve references like this one.
The reference points to another node in the same file.

I don't know how I would do this with the normal kotlinx.serialization api, but for the yaml parser itself this should be possible.

### Describe the solution you'd like

Could there be an option to enable that these references get resolved automatically?

**Comment by charleskorn** [comment]
Hi @jakobkmar, given this isn't a standard YAML feature, I'm not keen to add it to kaml.

kaml does already support YAML's anchors and aliases feature, which you could use to achieve the same result.

If you can't change the format of the file, I'd suggest either resolving the references in your application, or look at using a lower-level library like SnakeYAML.

**Comment by jakobkmar** [comment]
thank you for the quick reply

> I'd suggest either resolving the references in your application

do you have a suggestion how this can be done? the problem in my case is that this `parameter` property does not always contain a reference, sometimes it is a reference, sometimes the values are inlined

**Comment by charleskorn** [comment]
You could deserialise into a polymorphic type that represents either a concrete value or a reference, then go through and resolve the references to the concrete values

**Comment by jakobkmar** [comment]
I will have a look into that, thank you!

**Comment by jakobkmar** [comment]
If the content (in my example) can be either this:
 ```yml
parameters:
  - in: query
    name: index
    schema:
      type: string
      enum:
        - relevance
        - downloads
        - follows
        - newest
        - updated
      default: relevance
      example: downloads
 ```
 or this (with `$ref`):
 ```yml
 parameters:
  - $ref: "#/components/parameters/ProjectIdentifier"
 ```
 then how could this be represented using polymorphism?
 And which polymorphism style of kaml should I use in this case?
