### ISSUE TITLE
parent of YamlNode

### ISSUE THREAD

**Issue by Vampire** [charleskorn/kaml#31]
In some situations it would be handy to have the ability to navigate to the parent of a `YamlNode` like if presence of `value` in this example depends on the `using` value:
```
outputs:
    foo:
        description: bar
        value: baz

runs:
    using: composite
```
If you could navigate to the `YamlNode` you could use a custom serializer for `Output` that looks at the neighbor node.
Currently the only way I see is to have a custom serializer on the common parent of `outputs` and `runs` that recognizes the different cases.
