### ISSUE TITLE
can i do polymorphism with regex of keys?

### ISSUE THREAD

**Issue by NikkyAI** [charleskorn/kaml#46]
i have the followin YAML:

```yml
someid@typeA: 
  a: "a"
someOtherId@typeB:
  b: "b"
```

and would like to deserialize it into

```
sealed class Base {
	data class A(val a: String): Base()
	data class B(val b: String): Base()
}
```

obviously with a lot more fields
i am not sure how to pick a serializer for value based on key

would this be something handled in serialization or kaml ?
